name: generators
description: Getters and setters to save variables to and from Map
version: 1.0.2
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build:
  source_gen:

  annotations:
    git:
      url: https://github.com/amirsheibani/modelGeneratorsAnnotation.git
      ref: main # branch name
      version: 1.0.3

dev_dependencies:
  build_test:
  build_runner:
  test: ^1.0.0
